config/routes.rb
Mylinks::Application.routes.draw do
  
  root :to => 'pages#home'

  resources :links
  get "pages/home"

  devise_for :users

  match 'u/:id' => 'users#show', as: 'user'
  # match 'users/:username' => 'users#show', as: 'username'

  

  get "about" => "pages#about"




end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :address, :description, :linkname

  belongs_to :user

  validates :user_id, presence: true
  validates :linkname, :length => { :maximum => 50 }
  validates :address, uniqueness: true, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :bio, :motto
  # attr_accessible :title, :body

  # forces a unique username
  validates :username, :uniqueness => true

  # Create permalink when created
  before_save :create_permalink

  # linking links to user
  has_many :links
    
  def to_param
    permalink
  end

  private
    def create_permalink
      self.permalink = username.downcase
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


  before_filter :ensure_domain

  APP_DOMAIN = 'www.linkranger.me'

  def ensure_domain
  	if (request.env['HTTP_HOST'] != APP_DOMAIN )
  		# 
  		redirect_to "http://#{APP_DOMAIN}#{request.fullpath}", :status => 301 if ENV["RAILS_ENV"] == 'production'
  	end
  end

	def after_sign_in_path_for(resource)
	 links_path
	end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  #filter to prevent users not signed in from creating links
  before_filter :authenticate_user!, except: [:index]

  # GET /links
  # GET /links.json
  def index
    @links = current_user.links.all
    @links = current_user.links.paginate(page: params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/new
  # GET /links/new.json
  def new
    @link = current_user.links.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = current_user.links.find(params[:id])
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.json
  def update
    @link = current_user.links.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link = current_user.links.find(params[:id])
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!
	
	def show
		@user = User.find_by_permalink(params[:id])
	end

	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
  def url_with_protocol(url)
    /^http/.match(url) ? url : "http://#{url}"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		Link Ranger, created by 
		<%= link_to "Hunter Bacot", "http://hunterbacot.com" %>. Copyright 2013
	</small>	
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "Link Ranger", root_path, class: "brand"%>

      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      	<ul class="nav">
			<li><%= link_to "About", about_path %></li>
      <% if user_signed_in? %>
      <li><%= link_to "My Links", links_path %></li>
      <li><%= link_to "+Link", new_link_path %></li>
      <% end %>
		</ul>
		<ul class="nav pull-right">
      <% if user_signed_in? %>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %><b class="caret"></b></a>
          <ul class="dropdown-menu">
              <li><%= link_to "My Profile", user_path(current_user) %></li>
              <li><%= link_to "My Settings", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, :method=>'delete' %></li>
      <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
		</ul>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Mobile Viewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Link Ranger</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>
	<div class="container">
		<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
		<% end %>
		<%= yield %>
		<%= render "layouts/footer" %>
	</div>

</body>
</html>

app/views/links/_form.html.erb
<%= simple_form_for(@link) do |f| %>
  <%= f.error_notification %>
	  <div class="form-inputs">
	    <%= f.input :address, label: 'URL address' %>
	    <%= f.input :linkname, label: 'Title (optional)' %>
	    <%= f.input :description, label: 'Enter a brief description of your link (optional)' %>
	  </div>

	  <div class="form-actions">
	    <%= f.button :submit, class: "btn btn-primary" %>
	  </div>
<% end %>

app/views/links/edit.html.erb
<div class="row">
	<div class="span8 offset2">
		
		<h1>Edit your link</h1>
		<div class="well">

		<%= render 'form' %>

		<%= link_to 'Show', @link %> |
		<%= link_to 'Back', links_path %>
	</div>
	</div>
</div>

app/views/links/index.html.erb
<!-- <h1>Listing links</h1> -->

<div class="row">
  <div class="span10 offset1">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>My Links</th>
        <th>Description</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
    <% @links.each do |link| %>
      <tr>
        <% if link.linkname.blank? %>
        <td><%= link_to link.address, url_with_protocol(link.address), :target => '_blank' %></td>
        <% else %>
        <td><%= link_to link.linkname, url_with_protocol(link.address), :target => '_blank' %></td>
        <% end %>
        <td><%= link.description %></td>
        <td><%= link_to 'Show', link %></td>
        <% if current_user == link.user %>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Delete', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
    </table>
    <%= will_paginate @links %>
    <br />

    <%= link_to 'New Link', new_link_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/links/new.html.erb
<div class="row">
	<div class="span8 offset2">
		<h1>New link</h1>
		<div class="well">
			<%= render 'form' %>

			<%= link_to 'Back', links_path %>
		</div>
	</div>
</div>

app/views/links/show.html.erb
<div class="row">
	<div class="span8 offset2">
			<% unless @link.linkname.blank? %>
			<h2>
				<%= @link.linkname %>
			</h2>
			<% end %>
			<div class="well">
			<p>
			  <%= link_to @link.address, url_with_protocol(@link.address), :target => '_blank', class: 'big-link' %>
			</p>

			<p>
			  <%= @link.description %>
			</p>
			<br />

			<% if current_user == @link.user %>
			<%= link_to 'Edit', edit_link_path(@link) %> |
			<% end %>
			<%= link_to 'Back', links_path %> |
			<%= link_to 'New', new_link_path %>
		</div>
	</div>
</div>

app/views/pages/about.html.erb
<div class="row">
	<div class="span8 offset2">
		<h1>About Link Ranger</h1>
		<div class="well">
		<p>Link Ranger was created to present an easier alternative to storing links that you regularly access. Storing links through Link Ranger allows you to retrieve your links enywhere, without having to login to a broswer and sychronize your settings.</p>
		</div>
	</div>
</div>

app/views/pages/home.html.erb
<div class="hero-unit">
	<h1>Link Ranger</h1>
	<p>Link Ranger is a project that allows you to carry your bookmarks with you anywhere. There is no need to sync with every browser you use, just go to your links to view what you have saved with Link Ranger.</p>
	<p>
		<%= link_to "Register Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
	</p>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="span10 offset1">
			<div class="row">
				<div class="span5">
					<h1><%= @user.username %></h1>
					<p><i><%= @user.motto %></i></p>
				</div>
				<div class="span5">
					<h2>About <%= @user.username %></h2>
					<p>
						<%= @user.bio %>
					</p>
				</div>
			</div>
	</div>
</div>